language: node_js
node_js:
- node
install: npm install
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run coveralls
notifications:
  slack:
    secure: W6BC+0obn6/s7S4i8y+Dyu5S9Gq2ApAa+cWCOmBjgf4nmpck8c49WyOrfHjSKf7gviy9Vj5r9/0uhSJK/soEvmZku8mM+H6Yz7fN02B2eG26Ams5dS739pGcPm0d2xI2PxMznaFYd1rNGqYQAX6MoG9I38BvUOKD4CfN/iclMHRznVeSac3KUqjwiRB8G4AWl/dX+fi6kCpWeN18XIKIA/Sw0h1UdO2I4n70jlr5iGm/QMdduTObOdsoEKv4n4bLxuaZDuQGRCiusuZJJlLRpsAD8IiQXc7ZMpTeZ5xUokoSXAALU9FlTI0ggeZ1/taFlyOXMx43N+Vpw4JD+39+yO45wg8ho0gcxINRwfXmNN1zA/v07DCF39Z1TCiR9B8wOh5DxMKDWuITh4frjAemppWKkr2h5+AmOJI0NkJUpn1nbSmkL9F7+MtCXvloWkzYvLiqDi02xA3jQMEelbe3Pl6UQkyAC/0DmTdN8iwdtveyMsMe6ZgnYb8elEzf6XxlSUDr3X29UuhlHWHZJm8e9xJQ+f/UFDJ24refIykIKdCbagIgG85pjovVg4W5eTdX8darqVfUWzk/VnkNY9QbfWYj0QjLKqe2gN6sO5dL9Z/XY70lJ5adbdw13HErUlfTeKhLq9JNfqvOdlHnn0CQQb65VFPNVTZm7EuWFTspQWk=
deploy:
  provider: heroku
  api_key:
    secure: W+0vjdDeUmt3R2FVWl25BJJgYUCNFKW0x+K2+5qcNiPBKZmY32H+XxHdaSS3EhCDJAzqfGjfnmjcK8qPJVDVbjOZ8B0WXxps3YRz6mEyxvuDzEk9S+V70cr7oc1uM5BeEKHQbtBwRsE2ti8Fkgw8Z4QI9xl096W5szpEzgRJy4jj4gzNSu6TZTNn/HtNdCaeE36ss9bge2W3BSmUQoZ226PZoRq8sqKbh0afR1BBLwRClzmCXZUmSKxbZjCrp96WmodlwcD2QMFHaPn8JjmjXEDZDv7wM8VsQeyqnc6DEVThMUiwu8HKubMAjIYLRoXYgdZ0bQL7PUxemQoUol1hUqzrFVwIv1wNLDvRa9ftG1OD7zXjlLtp/9pvISx4ITeY5Jq4ShtOZu9+3g/xDKSMo/4HEecHbVnGmVXjw8J9YvtCWbv36MKGhBnVtDhp+xi21QnSMZ7hWzdf59DbpAY+tsG3CDRgVVdwJkEPB71wyjHygtI9VqyRuc7AxXU0gS2T8/ECiZNzL7c/QD80HdUwJng9UWZy9146sZES6wdkKccjR0ZqaO42+7ml4rZ+R7Qa646Po10UxbfaJiqhcTIIhXvTipSoc+n6L9Cfi54kLu4aZki+8+08L/61ml5WMrC7iayI46spRJZE1MdnJDklhzJTL9vhjz/d5G7YnE5JpT0=
  app:
    master: mentorpaired
    staging: mentorpaired-staging
