language: node_js
node_js:
- node
install: npm install
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run coveralls
notifications:
  slack:
    secure: W6BC+0obn6/s7S4i8y+Dyu5S9Gq2ApAa+cWCOmBjgf4nmpck8c49WyOrfHjSKf7gviy9Vj5r9/0uhSJK/soEvmZku8mM+H6Yz7fN02B2eG26Ams5dS739pGcPm0d2xI2PxMznaFYd1rNGqYQAX6MoG9I38BvUOKD4CfN/iclMHRznVeSac3KUqjwiRB8G4AWl/dX+fi6kCpWeN18XIKIA/Sw0h1UdO2I4n70jlr5iGm/QMdduTObOdsoEKv4n4bLxuaZDuQGRCiusuZJJlLRpsAD8IiQXc7ZMpTeZ5xUokoSXAALU9FlTI0ggeZ1/taFlyOXMx43N+Vpw4JD+39+yO45wg8ho0gcxINRwfXmNN1zA/v07DCF39Z1TCiR9B8wOh5DxMKDWuITh4frjAemppWKkr2h5+AmOJI0NkJUpn1nbSmkL9F7+MtCXvloWkzYvLiqDi02xA3jQMEelbe3Pl6UQkyAC/0DmTdN8iwdtveyMsMe6ZgnYb8elEzf6XxlSUDr3X29UuhlHWHZJm8e9xJQ+f/UFDJ24refIykIKdCbagIgG85pjovVg4W5eTdX8darqVfUWzk/VnkNY9QbfWYj0QjLKqe2gN6sO5dL9Z/XY70lJ5adbdw13HErUlfTeKhLq9JNfqvOdlHnn0CQQb65VFPNVTZm7EuWFTspQWk=
deploy:
  provider: heroku
  api_key:
    secure: sJ6lgusNqJvE8p9pRs+ZL6SfM1jrbjkgVyH5dhAv1EZ4xc6PnPxl5lQwfzDbev/XRgjjCPy4mPX4uP8aP1iMYhBYLLttDKzXEBmxXnbWN8tY4RAniGX/5s2ho9bCG+UXy6aG7db0OSdIaclBOzHpwRBkjDNpKysE0lluO/4tU9vNjMQ6RlgCvJGbUsxX8LFxnevlLDYFKax4dbw3eViwT1WbhlaW3ZFLtBn4HRl0+fCc2q43a+urrwoOPJIzEQxBMxzeX6hjzEFZBJDUDnpbQMKq8XYSlefbCrTQnkmSJCO9+5Pu7r1nG8zUgDXVMn0RzfOcy6iM+8u+WwCttbiJZPm1e2iYaChR4nGveEM0wZGzIDp8ORB3MlcmUiOLiL7eMzwXugY9cdmwdAHqFKOU9+aZ0Zi8YWl9zhGrjZkmxEaFdaldWLo5fh0MY5B2YWchgOIe3tItHGSBz+ld4Z24lrw2m2pti87tUbmluagIp1U/xpXU8TdZWegQoZthEbFqk4M1q1TURVp/tf+xrzyhc7FySR8uJeOnd2KQsInSvT+aDjwaRnRepahGYbQquyGCrNkV1dzRTQFd3FChQebh5hucIUD93YHwBLDhmOBk/qyu9w2jT6xvzWvkevaX/o4xkYuYPeLSscAcrtUAB9bATkEfJirhKXAXd6JDu0q7yv0=
  app:
    master: mentorpaired
    staging: mentorpaired-staging
