language: node_js
node_js:
- node
install: npm install
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run coveralls
notifications:
  slack:
    secure: W6BC+0obn6/s7S4i8y+Dyu5S9Gq2ApAa+cWCOmBjgf4nmpck8c49WyOrfHjSKf7gviy9Vj5r9/0uhSJK/soEvmZku8mM+H6Yz7fN02B2eG26Ams5dS739pGcPm0d2xI2PxMznaFYd1rNGqYQAX6MoG9I38BvUOKD4CfN/iclMHRznVeSac3KUqjwiRB8G4AWl/dX+fi6kCpWeN18XIKIA/Sw0h1UdO2I4n70jlr5iGm/QMdduTObOdsoEKv4n4bLxuaZDuQGRCiusuZJJlLRpsAD8IiQXc7ZMpTeZ5xUokoSXAALU9FlTI0ggeZ1/taFlyOXMx43N+Vpw4JD+39+yO45wg8ho0gcxINRwfXmNN1zA/v07DCF39Z1TCiR9B8wOh5DxMKDWuITh4frjAemppWKkr2h5+AmOJI0NkJUpn1nbSmkL9F7+MtCXvloWkzYvLiqDi02xA3jQMEelbe3Pl6UQkyAC/0DmTdN8iwdtveyMsMe6ZgnYb8elEzf6XxlSUDr3X29UuhlHWHZJm8e9xJQ+f/UFDJ24refIykIKdCbagIgG85pjovVg4W5eTdX8darqVfUWzk/VnkNY9QbfWYj0QjLKqe2gN6sO5dL9Z/XY70lJ5adbdw13HErUlfTeKhLq9JNfqvOdlHnn0CQQb65VFPNVTZm7EuWFTspQWk=
deploy:
  provider: heroku
  api_key:
    secure: Pf1jt/iOp5xsVW2pJxZSCrMWkGnx8wlnCj5LHy4sn+ZB1BEWj4DoXmb02OAEWkyyfcUV54X8CnjySf+WIn5FgEbQ6eRLoK+i+yemHlVA+vOfORItiCFrKCI3rIMz0ZB5RuYIKvgs5qpRKCW6s++TuPBz4SmwAYgdRKDi0WPt/ou0wvHyql/spAEfnpGdDewA7FjEMNnKmtRMTfx86INO5awbd+G8FT1kyjqoRZxXoiNE5ErvilMYZgwz+ghBzTm8yV8npRwwNGCLsJmb/oyFehPcS/ETCIHLwkqoSfwCUrgz9g/LovZ0MmSl5a1jLbfXP42g8MuPojQcWfipmG68PxXiSQoG5pgCEzPlpscbvNr3e8dg+qLyY48hTy75RLOIaynzgdjO04gu0Iybz7G5rTovsYMM6C+e1eSUZxeW06u0c9h12ayQY9FzZTBYFAXr1AO3wgAlqEDI+a9Fn63wWo5lIviC0LTcFQu0IGOIe6CQ1EVXPl+DPRC2DsnXvds0PYV18WGkaeQ5o1FNF2wAS9YdITWQhz4YINVFYzMrEWLCKAK/oEU+4vO3s7v3XqeVmIEDRBAH7GzhDluIWfhPjtTxa3uYwBsH3Gh2gjJVfdxdRrUwTU9t+gXBgY3hHLfSROqAHReBjZ/92Fw/3b9Jh5GY3mV/QLWBIbZQar/biqM=
  app:
    master: mentorpaired
    staging: mentorpaired-staging
