language: node_js
node_js:
  - 'node'
install: npm install
cache:
  directories:
    - 'node_modules'
script:
  - npm run test
  - npm run coveralls
notifications:
  slack:
    secure: W6BC+0obn6/s7S4i8y+Dyu5S9Gq2ApAa+cWCOmBjgf4nmpck8c49WyOrfHjSKf7gviy9Vj5r9/0uhSJK/soEvmZku8mM+H6Yz7fN02B2eG26Ams5dS739pGcPm0d2xI2PxMznaFYd1rNGqYQAX6MoG9I38BvUOKD4CfN/iclMHRznVeSac3KUqjwiRB8G4AWl/dX+fi6kCpWeN18XIKIA/Sw0h1UdO2I4n70jlr5iGm/QMdduTObOdsoEKv4n4bLxuaZDuQGRCiusuZJJlLRpsAD8IiQXc7ZMpTeZ5xUokoSXAALU9FlTI0ggeZ1/taFlyOXMx43N+Vpw4JD+39+yO45wg8ho0gcxINRwfXmNN1zA/v07DCF39Z1TCiR9B8wOh5DxMKDWuITh4frjAemppWKkr2h5+AmOJI0NkJUpn1nbSmkL9F7+MtCXvloWkzYvLiqDi02xA3jQMEelbe3Pl6UQkyAC/0DmTdN8iwdtveyMsMe6ZgnYb8elEzf6XxlSUDr3X29UuhlHWHZJm8e9xJQ+f/UFDJ24refIykIKdCbagIgG85pjovVg4W5eTdX8darqVfUWzk/VnkNY9QbfWYj0QjLKqe2gN6sO5dL9Z/XY70lJ5adbdw13HErUlfTeKhLq9JNfqvOdlHnn0CQQb65VFPNVTZm7EuWFTspQWk=
deploy:
  provider: heroku
  api_key:
    secure: tzGMlKDePUTlqLUGvrvEbWaoG7zCdj3dlxvGTgrXsKJICMbDeDVVXbjWBAkUVcVy6TSuGhvdFxt6fTjhvPPv4NIGLsLZBqpnBmwaGGZq/GIrI9yW58UnDaNb9ZVLSLaOhI8/qEoJfmhCVdeiYuRb7Gi837kwoj6fmEyWvSo67OvxCtAw/rkKy7RSpQArzhvH2VIhBJn48Tqx1YdMSujfOAVbKlmZbuCnBP1zdktdDoJGDMnu+o9dy4JguU7qC4ImVYoejZSyGDkeHC9vG7XYTgab5fnOahoOqTWr3TwubmjuWi6ABjNTqrDC6zyktlQs+EIvxp1ysueKYAWg7AXA7t73OeulG7ikHEHegJJouopk02x7pzsUM7oz6CClKuhP8h8VevUo4FbcAuR/Ap2nsozo1GZCvsEgrrGGHNJU0ckn2HS3AtJb1bve1sGoa2h4138FF9ttSm/VS7fsyAOYuTCN/qKgsCe87GYkbXavQJHVJfE3eQ0SzpCDyWYxrU09w5Q+q9NyuhUrM6So8+Rkfc+zasJLmtiDrNUW9rDfwgkfIv0ulGg5T/SsypFDWV6kNhtm8XNMmRk3I/bq18B3SDVNCTluJROCXDIam57SoxWykL6Tx5hizSig7QX/WRreVNIDpBQWbvtlk6f2N1wO2miFfqnGx0XBQQohG1OwQKU=
  app:
    master: mentorpaired
    staging: mentorpaired-staging
