language: node_js
node_js:
  - node
install: npm install
cache:
  directories:
    - node_modules
script:
notifications:
  slack:
    secure: W6BC+0obn6/s7S4i8y+Dyu5S9Gq2ApAa+cWCOmBjgf4nmpck8c49WyOrfHjSKf7gviy9Vj5r9/0uhSJK/soEvmZku8mM+H6Yz7fN02B2eG26Ams5dS739pGcPm0d2xI2PxMznaFYd1rNGqYQAX6MoG9I38BvUOKD4CfN/iclMHRznVeSac3KUqjwiRB8G4AWl/dX+fi6kCpWeN18XIKIA/Sw0h1UdO2I4n70jlr5iGm/QMdduTObOdsoEKv4n4bLxuaZDuQGRCiusuZJJlLRpsAD8IiQXc7ZMpTeZ5xUokoSXAALU9FlTI0ggeZ1/taFlyOXMx43N+Vpw4JD+39+yO45wg8ho0gcxINRwfXmNN1zA/v07DCF39Z1TCiR9B8wOh5DxMKDWuITh4frjAemppWKkr2h5+AmOJI0NkJUpn1nbSmkL9F7+MtCXvloWkzYvLiqDi02xA3jQMEelbe3Pl6UQkyAC/0DmTdN8iwdtveyMsMe6ZgnYb8elEzf6XxlSUDr3X29UuhlHWHZJm8e9xJQ+f/UFDJ24refIykIKdCbagIgG85pjovVg4W5eTdX8darqVfUWzk/VnkNY9QbfWYj0QjLKqe2gN6sO5dL9Z/XY70lJ5adbdw13HErUlfTeKhLq9JNfqvOdlHnn0CQQb65VFPNVTZm7EuWFTspQWk=
deploy:
  provider: heroku
  api_key:
    secure: ld4oI5nC2UaSq629Raf3wATrNMGSfJBCnGdnaIxR8vk5VEI3hiKSbzmfzsBAc3Zf4Gnq9CVEKbylAtLg1kNy9cr8eRgnTXZt8R/N56qjF0BWcEkZQz7Ho7D3BHuSpgpdP4khmotFrc75eE201r+FCNJkoqb5ziL7V4EWPeqWjWxFjwCCRtSenypPfp075yO9j3CeYyEeCku0+JQmyrdrR0cUGY0KC+dVNPJreKyzGlDx1q6IUKDMmyX97JNQQwq44m8ZtuuhNacWvfUMX43Fap+zK3VkWgVP0kHZr1fTCFjCa56JgMTayuM2QbXtq5zxL2F2fEzTZy2ottxuZTSZyMSrOIsHo6n+BK4vnKP98o3v6/YrDUvQ4T9WPbRZcuIvAPB8AGdXy4aFqScOfITdiV2/Wi3YVsAfkCByL3HWi6vbaZkP0HMZInqStHOGzF6JaNolLqFMHpMsRPmrxITXWmbBdyaa7XP6fvALf7VOyn70apkj+C+l6GJzpGcyqiXs4cxC9+LS3WuxEyyPIYAhHVJeu7elFuZL7tOHpfD2JEIuY8eJnHTlXzKoZ9QvW123HZklphFUW4PeuBVFINA38RmAb4Rh6yDXwz3akxeQo3gvJhjAn+guLfjTi/uY3e0gz6Q9+CIMOZjvuTyIudSd/UWXlwjtwAzxMIa9d/9iVac=
  app:
    master: mentorpaired
    staging: mentorpaired-staging
