export const LOADING = "LOADING";
export const AUTHENTICATED = "AUTHENTICATED";
export const GITHUB_LOGIN_SUCCESS = "GITHUB_LOGIN_SUCCESS";
export const GITHUB_LOGIN_FAIL = "GITHUB_LOGIN_FAIL";
export const GITHUB_LOGOUT = "GITHUB_LOGOUT";
export const LOAD_USER_INFO = "LOAD_USER_INFO";
export const LOAD_USER_INFO_ERROR = "LOAD_USER_INFO_ERROR";
