export const LOADING = "LOADING";
export const AUTHENTICATED = "AUTHENTICATED";
export const GITHUB_LOGIN_SUCCESS = "GITHUB_LOGIN_SUCCESS";
export const GITHUB_LOGIN_FAIL = "GITHUB_LOGIN_FAIL";
export const GITHUB_LOGOUT = "GITHUB_LOGOUT";
export const RETRIEVING_USER_INFO = "RETRIEVING_USER_INFO";
export const RETRIEVED_USER_INFO = "RETRIEVED_USER_INFO";
export const RETRIEVE_USER_INFO_ERROR = "RETRIEVE_USER_INFO_ERROR";
